version: "3.9"
services:
  test:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: python3 -m pytest
  run:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: python3 app/run.py
